# 繰り返し使う設定のテンプレート
x-bot-template: &bot-template
  build: .
  restart: unless-stopped
  environment:
    # ▼▼▼ あなたの環境に合わせて書き換えてください ▼▼▼
    MC_HOST: 'bot-velocity'
    MC_PORT: 25577
    MC_AUTH: 'offline'
    MC_VERSION: '1.20.1'
    # ▲▲▲ ここまで ▲▲▲

# 起動するサービス（ボット）を定義
services:
  bot00:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot00
    networks:
      - home-network
  bot01:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot01
    networks:
      - home-network

  bot02:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot02
    networks:
      - home-network

  bot03:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot03
    networks:
      - home-network

  bot04:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot04
    networks:
      - home-network

  bot05:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot05
    networks:
      - home-network

  bot06:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot06
    networks:
      - home-network

  bot07:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot07
    networks:
      - home-network

  bot08:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot08
    networks:
      - home-network

  bot09:
    <<: *bot-template
    environment:
      MC_HOST: 'bot-velocity'
      MC_PORT: 25577
      MC_AUTH: 'offline'
      MC_VERSION: '1.20.1'
      MC_USERNAME: bot09
    networks:
      - home-network

networks:
  home-network:
    external: true
    name: home-network
